import React from "react";
import { Comment } from "react-loader-spinner";

export class ChatAssistant extends React.Component<any,any> {
  
    render() {
        

         let className: string = this.props.className;
         let imageIcon: string = this.props.imageIcon;
         let imageAlt:string= this.props.imageAlt;
         let isProcessing:boolean= this.props.isProcessing;
        let content:string=this.props.content;
        let time:Date=this.props.time;
        
        let isQueryResponse:boolean = this.props.isQueryResponse;
        return(
            <div>
            <div
                className={className}
            >
              {!isProcessing &&  <span
                    className="fbot-bubble-src"
                >
                  <img
                        src={imageIcon}
                        alt={imageAlt} className="user-img"
                    ></img>
                    
                </span>
    }
             {isProcessing &&  
                    <Comment
  visible={true}
  height="40"
  width="40"
  ariaLabel="comment-loading"
  wrapperStyle={{}}
  wrapperClass="comment-wrapper"
  color="#fff"
  backgroundColor="#F4442E">
  </Comment>  
    }
    {
        !isProcessing && <span
        className="fbot-bubble-bot-text">
       { content}
           </span> 
           
    }
     
                { isQueryResponse &&  <div><span
                    className="fbot-disclaimer-text"
                >
                   DISCLAIMER : The responses generated by me are subject to human verification for accuracy and correctness.
                </span></div>
    }
        </div>
        <div className="fbot-bubble-bot-time">{time}</div>
        </div>
        )
    }
}